export const FETCH_ARTICLES_REQUEST = 'FETCH_ARTICLES_REQUEST';
export const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS';
export const FETCH_ARTICLES_FAILURE = 'FETCH_ARTICLES_FAILURE';

export const FETCH_ARTICLE_FULL_REQUEST = 'FETCH_ARTICLE_FULL_REQUEST';
export const FETCH_ARTICLE_FULL_SUCCESS = 'FETCH_ARTICLE_FULL_SUCCESS';
export const FETCH_ARTICLE_FULL_FAILURE = 'FETCH_ARTICLE_FULL_FAILURE';

export const POST_REGISTRATION = 'POST_REGISTRATION';
export const POST_REGISTRATION_SUCCESS = 'POST_REGISTRATION_SUCCESS';
export const POST_REGISTRATION_FAILURE = 'POST_REGISTRATION_FAILURE';
export const POST_REGISTRATION_SERVER_FAILURE = 'POST_REGISTRATION_SERVER_FAILURE';

export const POST_LOGIN = 'POST_LOGIN';
export const POST_LOGIN_SUCCESS = 'POST_LOGIN_SUCCESS';
export const POST_LOGIN_FAILURE = 'POST_LOGIN_FAILURE';
export const POST_LOGIN_SERVER_FAILURE = 'POST_LOGIN_SERVER_FAILURE';

export const GET_CURRENT_USER = 'GET_CURRENT_USER';

export const LOG_OUT = 'LOG_OUT';

export const PUT_EDIT_PROFILE = 'PUT_EDIT_PROFILE';
export const PUT_EDIT_PROFILE_SUCCESS = 'PUT_EDIT_PROFILE_SUCCESS';
export const PUT_EDIT_PROFILE_FAILURE = 'PUT_EDIT_PROFILE_FAILURE';
export const PUT_EDIT_PROFILE_SERVER_FAILURE = 'PUT_EDIT_PROFILE_SERVER_FAILURE';
